// Generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Identity of the running build, shown in Settings → About and used by the update
	 *  check to decide whether a newer release exists.
	 */
	appInfo: () => typedError<AppInfo, ErrorPayload>(__TAURI_INVOKE("app_info")),
	/**
	 *  Microphones available right now, default first.
	 * 
	 *  cpal has no device-change notification, so the frontend re-queries rather than
	 *  caching.
	 */
	listMicrophones: () => typedError<MicrophoneInfo[], ErrorPayload>(__TAURI_INVOKE("list_microphones")),
	/**  Every model Kiku can install, with what is on disk right now. */
	listModels: () => typedError<ModelInfo[], ErrorPayload>(__TAURI_INVOKE("list_models")),
	/**
	 *  Download and install a model, emitting `DownloadProgressed` as it goes.
	 * 
	 *  Awaited by the caller so onboarding can show a completion state, while progress
	 *  arrives out of band.
	 */
	downloadModel: (modelId: string) => typedError<null, ErrorPayload>(__TAURI_INVOKE("download_model", { modelId })),
	/**
	 *  Remove an installed model, freeing its disk space.
	 * 
	 *  If it is the model currently loaded, the recogniser is unloaded first and another
	 *  installed model is loaded in its place - deleting one model must not leave
	 *  dictation broken when another is available.
	 */
	deleteModel: (modelId: string) => typedError<null, ErrorPayload>(__TAURI_INVOKE("delete_model", { modelId })),
	/**
	 *  Switch to a different installed model.
	 * 
	 *  Returns once the model is loaded, since the caller wants to know when dictation is
	 *  usable again rather than when the request was accepted.
	 */
	useModel: (modelId: string) => typedError<EngineStatus, ErrorPayload>(__TAURI_INVOKE("use_model", { modelId })),
	/**
	 *  Re-hash an installed model against its pinned checksums.
	 * 
	 *  Slow by design - this is the repair path, not a startup check.
	 */
	verifyModel: (modelId: string) => typedError<null, ErrorPayload>(__TAURI_INVOKE("verify_model", { modelId })),
	/**  Whether the recogniser is ready, loading, or failed. */
	engineStatus: () => typedError<EngineStatus, ErrorPayload>(__TAURI_INVOKE("engine_status")),
	/**  The dictation hotkeys currently registered. */
	hotkeyBindings: () => typedError<HotkeyBindings, ErrorPayload>(__TAURI_INVOKE("hotkey_bindings")),
	/**
	 *  Validate a shortcut without registering it, so a rebinding UI can give immediate
	 *  feedback as the user types.
	 */
	validateHotkey: (spec: string) => typedError<Hotkey, ErrorPayload>(__TAURI_INVOKE("validate_hotkey", { spec })),
	/**
	 *  Register a new pair of dictation shortcuts.
	 * 
	 *  Both are validated before anything is unregistered, so a typo cannot take the
	 *  working shortcuts away.
	 */
	setHotkeys: (bindings: HotkeyBindings) => typedError<HotkeyBindings, ErrorPayload>(__TAURI_INVOKE("set_hotkeys", { bindings })),
	/**
	 *  Open a link in the user's browser.
	 * 
	 *  The only outbound link in the application is the GitHub release page, which is why
	 *  this exists at all.
	 */
	openUrl: (url: string) => typedError<null, ErrorPayload>(__TAURI_INVOKE("open_url", { url })),
	/**  Whether Kiku is idle, listening or transcribing. */
	dictationState: () => typedError<DictationState, ErrorPayload>(__TAURI_INVOKE("dictation_state")),
	/**  Abandon the current recording without transcribing it. */
	cancelDictation: () => typedError<null, ErrorPayload>(__TAURI_INVOKE("cancel_dictation")),
	/**  Choose the microphone. `None` follows the system default. */
	setMicrophone: (deviceId: string | null) => typedError<null, ErrorPayload>(__TAURI_INVOKE("set_microphone", { deviceId })),
	/**  How transcripts are delivered and whether sounds play. */
	preferences: () => typedError<Preferences, ErrorPayload>(__TAURI_INVOKE("preferences")),
	setPreferences: (preferences: Preferences) => typedError<null, ErrorPayload>(__TAURI_INVOKE("set_preferences", { preferences })),
	/**
	 *  Play a cue so the user can hear it while adjusting the setting.
	 * 
	 *  Deliberately ignores the sounds preference: previewing is the one place a user
	 *  wants to hear a cue they have currently switched off.
	 */
	previewSound: (cue: SoundCue) => typedError<null, ErrorPayload>(__TAURI_INVOKE("preview_sound", { cue })),
	/**  A page of past dictations, newest first, optionally filtered by a search. */
	listHistory: (query: string | null, limit: number, offset: number) => typedError<Page, ErrorPayload>(__TAURI_INVOKE("list_history", { query, limit, offset })),
	/**  Delete one entry. */
	deleteHistoryEntry: (id: number) => typedError<boolean, ErrorPayload>(__TAURI_INVOKE("delete_history_entry", { id })),
	/**  Delete every entry. Returns how many went. */
	clearHistory: () => typedError<number, ErrorPayload>(__TAURI_INVOKE("clear_history")),
	/**  Delete entries older than `days`. Returns how many went. */
	purgeHistory: (days: number) => typedError<number, ErrorPayload>(__TAURI_INVOKE("purge_history", { days })),
	/**
	 *  Whether a newer Kiku has been published.
	 * 
	 *  Uses a result cached for a day unless `force` is set, and reports `Unknown` rather
	 *  than an error when offline - a failed update check is not something to interrupt
	 *  someone about.
	 */
	checkForUpdate: (force: boolean) => typedError<UpdateStatus, ErrorPayload>(__TAURI_INVOKE("check_for_update", { force })),
};

/** Events */
export const events = {
	dictationDiscarded: makeEvent<DictationDiscarded>("dictation-discarded"),
	dictationStateChanged: makeEvent<DictationStateChanged>("dictation-state-changed"),
	downloadProgressed: makeEvent<DownloadProgressed>("download-progressed"),
	engineStatusChanged: makeEvent<EngineStatusChanged>("engine-status-changed"),
	levelMeasured: makeEvent<LevelMeasured>("level-measured"),
	transcriptProduced: makeEvent<TranscriptProduced>("transcript-produced"),
};

/* Types */
export type AppInfo = {
	version: string,
	identifier: string,
	platform: string,
};

/**  Emitted when a dictation finished but produced nothing worth keeping. */
export type DictationDiscarded = Discarded;

export type DictationState = { state: "idle" } | { state: "listening" } | { state: "processing" };

/**  Emitted as dictation moves between idle, listening and processing. */
export type DictationStateChanged = DictationState;

/**  Why a session produced no text. */
export type Discarded = 
/**  Released the key almost immediately - a mistap, not an utterance. */
"tooShort" | 
/**  The microphone captured effectively nothing. */
"silent" | 
/**  The recogniser heard audio but produced no words. */
"noSpeech";

/**
 *  Progress for the model as a whole, not the individual file, because that is what a
 *  progress bar should show.
 * 
 *  Byte counts cross the boundary as `u32`. Specta rejects `u64` there to prevent
 *  silent precision loss, and maps every float to `number | null` because NaN cannot
 *  be represented in JSON - so a float would push a null into every call site. `u32`
 *  caps a model at four gigabytes, which is far beyond anything a lightweight
 *  dictation tool would ship.
 */
export type DownloadProgress = {
	downloadedBytes: number,
	totalBytes: number,
};

/**  Emitted repeatedly while a model downloads. */
export type DownloadProgressed = DownloadProgress;

/**  What the UI needs to know about the recogniser. */
export type EngineStatus = 
/**  No model installed yet - onboarding has not finished. */
{ state: "unloaded" } | 
/**  Loading into memory; a hotkey pressed now should say "getting ready". */
{ state: "loading" } | 
/**  Ready to transcribe. Carries the model identifier. */
{ state: "ready"; detail: string } | 
/**  Loading failed. Carries a sentence fit to show the user. */
{ state: "failed"; detail: string };

/**  Emitted when the recogniser's state changes, so the UI never has to poll. */
export type EngineStatusChanged = EngineStatus;

/**
 *  A stored dictation.
 * 
 *  The wire types are chosen so nothing crosses the boundary as a float. Specta maps
 *  every Rust float to `number | null`, because NaN and infinity serialise as null,
 *  and threading that null through the whole interface would be a poor trade for
 *  values that are conceptually integers and instants.
 */
export type Entry = {
	/**
	 *  SQLite rowid. `u32` allows four billion dictations, which at a thousand a day
	 *  is eleven thousand years.
	 */
	id: number,
	text: string,
	/**  RFC 3339 in UTC - self-describing, exact, and parsed natively by `Date`. */
	createdAt: string,
	audioMs: number,
	decodeMs: number,
	modelId: string | null,
};

export type ErrorPayload = {
	kind: string,
	message: string,
};

export type Hotkey = {
	/**  Portable specification, for example `Ctrl+Alt+Space`. */
	spec: string,
	/**  Rendered for this platform, for example `⌃⌥Space` on macOS. */
	display: string,
};

export type HotkeyBindings = {
	hold: Hotkey,
	toggle: Hotkey,
};

export type InstallState = 
/**  Nothing on disk. */
{ state: "missing" } | 
/**
 *  A download was interrupted; bytes already fetched. See `DownloadProgress` for
 *  why byte counts cross the boundary as `u32`.
 */
{ state: "partial"; detail: {
	downloaded: number,
} } | 
/**  All files present at the expected sizes. */
{ state: "installed" };

export type Level = {
	/**  Root mean square of the buffer, 0.0..=1.0. Perceptually the useful one. */
	rms: number | null,
	/**  Largest absolute sample in the buffer, 0.0..~1.0. */
	peak: number | null,
	/**  Whether any sample in the buffer reached full scale. */
	clipped: boolean,
	/**
	 *  How far above the learned noise floor this is, 0..1 - what the waveform draws.
	 * 
	 *  Filled in by [`SpeechLevel`](super::SpeechLevel) once a session is running,
	 *  because it needs history that a single buffer does not have. Zero until then.
	 */
	speech: number | null,
};

/**  Emitted about fourteen times a second while recording, to drive the waveform. */
export type LevelMeasured = Level;

export type MicrophoneInfo = {
	/**  Persistable handle, from `DeviceId`'s `Display` implementation. */
	id: string,
	name: string,
	isDefault: boolean,
};

export type ModelInfo = {
	id: string,
	name: string,
	summary: string,
	/**  See `DownloadProgress` for why byte counts cross the boundary as `u32`. */
	totalBytes: number,
	install: InstallState,
	/**  Whether this is the model the recogniser currently has loaded. */
	active: boolean,
};

/**  A page of history. */
export type Page = {
	entries: Entry[],
	/**  Total matching rows, so the UI can say "showing 50 of 1,204". */
	total: number,
};

/**
 *  User preferences that affect how a transcript is delivered.
 * 
 *  Persisted to disk in chunk 10; held here so the rest of the application can already
 *  read them from one place.
 */
export type Preferences = {
	/**  Paste into the focused window after copying. The copy always happens. */
	autoPaste: boolean,
	/**  Append one space, so consecutive dictations do not run together. */
	trailingSpace: boolean,
	/**  Play the short tones that mark listening starting and finishing. */
	sounds: boolean,
	/**  Stop recording dictations to history. The existing history is left alone. */
	historyPaused: boolean,
	/**  Delete history entries older than this many days. `None` keeps everything. */
	retentionDays: number | null,
	/**  Ask GitHub once a day whether a newer release exists. Never downloads. */
	checkForUpdates: boolean,
	/**
	 *  Which model to load. `None` means "whichever is installed", which is what a
	 *  fresh install and a single-model setup both want.
	 */
	modelId: string | null,
};

/**  Which feedback cue to preview from Settings. */
export type SoundCue = 
/**  Kiku started listening. */
"start" | 
/**  Kiku stopped listening. */
"stop";

export type Transcript = {
	/**  Recognised text, already punctuated and capitalised by the model. */
	text: string,
	/**  Length of the audio that produced it. */
	audioMs: number,
	/**  Wall-clock time the decode took. */
	decodeMs: number,
};

/**  Emitted when a dictation produced text. */
export type TranscriptProduced = Transcript;

/**  What the UI shows. */
export type UpdateStatus = 
/**  Running the newest published release, or a build ahead of it. */
{ state: "upToDate" } | 
/**  A newer release exists. */
{ state: "available"; detail: {
	version: string,
	url: string,
} } | 
/**  Nothing known - offline, switched off, or not yet checked. */
{ state: "unknown" };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

