//! Kiku — offline dictation.
//!
//! Modules are organised by domain rather than by layer, so a change to "how audio is
//! captured" touches one directory instead of being spread across `services/`,
//! `utils/` and `helpers/`.

pub mod asr;
pub mod audio;
pub mod error;
mod ipc;

pub use error::{CommandResult, Error, ErrorPayload, Result};

use tauri::Manager;
use tauri_specta::{collect_commands, Builder};

/// The single source of truth for the IPC surface.
///
/// Used twice: once by `run` to register the handlers, and once by the `bindings` test
/// to generate `src/lib/ipc/bindings.ts`. Because both read the same builder, a Rust
/// signature change is a TypeScript compile error rather than a runtime surprise.
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![ipc::app_info, ipc::list_microphones])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "kiku=info,warn".into()),
        )
        .init();

    let builder = specta_builder();

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_global_shortcut::Builder::new().build())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            // The overlay window is created at launch and merely hidden, never created
            // on demand: creating an OS window costs 30-120ms of visible lag, which is
            // most of the latency budget for the whole press-to-paint path.
            if let Some(overlay) = app.get_webview_window("overlay") {
                overlay.set_ignore_cursor_events(true)?;
            }

            if let Some(main) = app.get_webview_window("main") {
                main.show()?;
            }

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Kiku");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerates the TypeScript bindings. Run with `cargo test export_bindings`.
    /// Kept as a test so type generation can never be linked into a release binary.
    #[test]
    fn export_bindings() {
        specta_builder()
            .export(
                specta_typescript::Typescript::default()
                    .header("// Generated by tauri-specta. Do not edit.\n"),
                "../src/lib/ipc/bindings.ts",
            )
            .expect("failed to export TypeScript bindings");
    }
}
